/** @format */

//aca van las actions typo: ACA_VAN_LAS_ACTIONS = 'ACA VAN LAS ACTIONS'

export const GET_PRODUCTOS = "GET_PRODUCTOS";
export const GET_PRODUCTO_NOMBRE = "GET_PRODUCTO_NOMBRE";
export const PUT_PRODUCTO = "PUT_PRODUCTO";
export const DELETE_PRODUCTO = "DELETE_PRUDUCTO";

export const GET_DESCUENTOS = "GET_DESCUENTOS";
export const GET_NAME = "GET_NAME";
export const CLEAN = "CLEAN";

export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_BY_CATEGORIES = "GET_BY_CATEGORIES";
export const ORDER_BY_PRICE = "ORDER_BY_PRICE";
export const GET_SUBCATEGORIES = "GET_SUBCATEGORIES";

export const GET_USUARIOS = "GET_USUARIOS";
export const GET_USUARIOS_NOMBRE = "GET_USUARIOS_NOMBRE";
export const DELETE_USUARIO = "DELETE_USUARIO";
export const GET_USUARIOS_ID = "GET_USUARIOS_ID";
export const PUT_USUARIOS_ID = "PUT_USUARIOS_ID";
export const PUT_PRECIOS_ID = "PUT_PRECIOS_ID";
