/** @format */

//aca van las actions typo: ACA_VAN_LAS_ACTIONS = 'ACA VAN LAS ACTIONS'

export const GET_PRODUCTOS = "GET_PRODUCTOS";
export const GET_PRODUCTO_NOMBRE = "GET_PRODUCTO_NOMBRE";
export const PUT_PRODUCTO = "PUT_PRODUCTO";
export const DELETE_PRODUCTO = "DELETE_PRUDUCTO";

export const GET_DESCUENTOS = "GET_DESCUENTOS";
export const GET_NAME = "GET_NAME";
export const CLEAR = "CLEAR";

export const CREATE_MERCADO_PAGO_PREFERENCE = "CREATE_MERCADO_PAGO_PREFERENCE";

export const GET_DIRECCION = "GET_DIRECCION";
export const POST_LOCATION = "POST_LOCATION ";
export const POST_USUARIO = "POST_USUARIO";
export const PUT_LOCATION = "PUT_LOCATION";

export const GET_TOKEN = "GET_TOKEN";
export const POST_COMENTS = "COMENTS";
export const GET_COMENTARIOS = "GET_COMENTARIOS";
export const POST_CALIFICACION = "POST_CALIFICACION";
export const GET_CALIFICACIONES = "GET_CALIFICACIONES";

export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_BY_CATEGORIES = "GET_BY_CATEGORIES";
export const ORDER_BY_PRICE = "ORDER_BY_PRICE";
export const GET_SUBCATEGORIES = "GET_SUBCATEGORIES";
export const GET_MARCAS = "GET_MARCAS";
export const FILTER_BY_MARCAS = "FILTER_BY_MARCAS";

export const SAVE_ID = "SAVE_ID";

export const FILTER_ARMA_TU_PC = "FILTER_ARMA_TU_PC";
export const FILTER_COMPONENTES_ARMATUPC = "FILTER_COMPONENTES_ARMATUPC";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export const GET_USUARIOS = "GET_USUARIOS";
export const GET_USUARIOS_NOMBRE = "GET_USUARIOS_NOMBRE";
export const DELETE_USUARIO = "DELETE_USUARIO";
export const GET_USUARIOS_ID = "GET_USUARIOS_ID";
export const PUT_USUARIOS_ID = "PUT_USUARIOS_ID";
export const PUT_PRECIOS_ID = "PUT_PRECIOS_ID";

export const UPDATE_CARRITO = "UPDATE_CARRITO";
export const FETCH_SPECIFICATIONS_3 = "FETCH_SPECIFICATIONS_3";
export const FETCH_SPECIFICATIONS_9 = "FETCH_SPECIFICATIONS_9";
export const FETCH_SPECIFICATIONS_30 = "FETCH_SPECIFICATIONS_30";

export const GET_PEDIDOS_ID = "GET_PEDIDOS_ID";
export const PUT_ORDER_STATUS = "PUT_ORDER_STATUS";
export const GET_ELIMINADOS = "GET_ELIMINADOS";
export const REMOVE_TOKEN = "REMOVE_TOKEN";

export const UPDATE_CART_QUANTITY = "UPDATE_CART_QUANTITY";
